import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '../styles/globals.css';
import Provider from '@/providers/SessionProvider';
import { Toaster } from '@/components/ui/toaster';
import QueryProvider from '@/providers/QueryProvider';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} min-h-screen w-full antialiased`}>
        <Provider>
          <QueryProvider>{children}</QueryProvider>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
